import { Application, AppTier, AppValue } from './types';

export const INITIAL_APPS: Application[] = [
  {
    id: '1',
    name: 'Nexus Customer Portal',
    code: 'APP-001',
    tier: AppTier.CHANNEL,
    description: 'Main customer facing portal for order entry.',
    owner: 'Sarah Connor',
    domain: 'Commercial',
    capabilityId: 'CAP-SALES',
    security: { gdprCompliant: true, piiRisk: 'HIGH', lastPenTest: '2023-10-01' },
    technicalDebt: 'LOW',
    health: 85,
    value: AppValue.CRITICAL,
    dataSensitivity: 'CONFIDENTIAL',
    lifecycle: { status: 'ACTIVE' },
    costs: { license: 80000, maintenance: 40000, total: 120000 },
    upstreamIds: [],
    downstreamIds: ['2', '3']
  },
  {
    id: '2',
    name: 'MuleSoft API Gateway',
    code: 'APP-002',
    tier: AppTier.INTEGRATION,
    description: 'Enterprise integration layer.',
    owner: 'John Smith',
    domain: 'IT',
    capabilityId: 'CAP-IT',
    security: { gdprCompliant: true, piiRisk: 'NONE' },
    technicalDebt: 'LOW',
    health: 90,
    value: AppValue.HIGH,
    dataSensitivity: 'INTERNAL',
    lifecycle: { status: 'ACTIVE' },
    costs: { license: 200000, maintenance: 50000, total: 250000 },
    upstreamIds: ['1'],
    downstreamIds: ['4', '5']
  },
  {
    id: '3',
    name: 'Salesforce CRM',
    code: 'APP-003',
    tier: AppTier.CORE,
    description: 'Customer relationship management system of record.',
    owner: 'Jane Doe',
    domain: 'Commercial',
    capabilityId: 'CAP-SALES',
    security: { gdprCompliant: false, piiRisk: 'HIGH' },
    technicalDebt: 'MEDIUM',
    health: 65,
    value: AppValue.CRITICAL,
    dataSensitivity: 'RESTRICTED',
    lifecycle: { status: 'ACTIVE' },
    costs: { license: 350000, maintenance: 100000, total: 450000 },
    upstreamIds: ['1'],
    downstreamIds: ['6']
  },
  {
    id: '4',
    name: 'SAP ERP Core',
    code: 'APP-004',
    tier: AppTier.CORE,
    description: 'Legacy ERP system. Requires migration.',
    owner: 'Hans Gruber',
    domain: 'Finance',
    capabilityId: 'CAP-FINANCE',
    security: { gdprCompliant: true, piiRisk: 'HIGH' },
    technicalDebt: 'HIGH',
    health: 40,
    value: AppValue.CRITICAL,
    dataSensitivity: 'RESTRICTED',
    lifecycle: { status: 'EOL', validUntil: '2024-12-31' },
    costs: { license: 800000, maintenance: 400000, total: 1200000 },
    upstreamIds: ['2'],
    downstreamIds: ['7']
  },
  {
    id: '5',
    name: 'Logistics Tracker',
    code: 'APP-005',
    tier: AppTier.CORE,
    description: 'Tracks shipments.',
    owner: 'Ellen Ripley',
    domain: 'Supply Chain',
    capabilityId: 'CAP-LOGISTICS',
    security: { gdprCompliant: true, piiRisk: 'LOW' },
    technicalDebt: 'MEDIUM',
    health: 60,
    value: AppValue.STANDARD,
    dataSensitivity: 'INTERNAL',
    lifecycle: { status: 'PHASE_OUT' },
    costs: { license: 50000, maintenance: 35000, total: 85000 },
    upstreamIds: ['2'],
    downstreamIds: []
  },
  {
    id: '6',
    name: 'Data Warehouse (Snowflake)',
    code: 'APP-006',
    tier: AppTier.INFRA,
    description: 'Central analytics storage.',
    owner: 'Morpheus',
    domain: 'IT',
    capabilityId: 'CAP-IT',
    security: { gdprCompliant: true, piiRisk: 'HIGH' },
    technicalDebt: 'LOW',
    health: 95,
    value: AppValue.HIGH,
    dataSensitivity: 'CONFIDENTIAL',
    lifecycle: { status: 'ACTIVE' },
    costs: { license: 300000, maintenance: 20000, total: 320000 },
    upstreamIds: ['3', '4'],
    downstreamIds: []
  },
  {
    id: '7',
    name: 'Mainframe Payment Switch',
    code: 'APP-007',
    tier: AppTier.INFRA,
    description: 'End of life payment switch.',
    owner: 'Neo',
    domain: 'Finance',
    capabilityId: 'CAP-FINANCE',
    security: { gdprCompliant: true, piiRisk: 'HIGH' },
    technicalDebt: 'HIGH',
    health: 20,
    value: AppValue.CRITICAL,
    dataSensitivity: 'RESTRICTED',
    lifecycle: { status: 'EOL' },
    costs: { license: 500000, maintenance: 390000, total: 890000 },
    upstreamIds: ['4'],
    downstreamIds: []
  },
  {
    id: '8',
    name: 'Marketing Site',
    code: 'APP-008',
    tier: AppTier.CHANNEL,
    description: 'Public facing brochureware.',
    owner: 'Don Draper',
    domain: 'Commercial',
    capabilityId: 'CAP-MARKETING',
    security: { gdprCompliant: true, piiRisk: 'NONE' },
    technicalDebt: 'LOW',
    health: 80,
    value: AppValue.STANDARD,
    dataSensitivity: 'PUBLIC',
    lifecycle: { status: 'ACTIVE' },
    costs: { license: 10000, maintenance: 5000, total: 15000 },
    upstreamIds: [],
    downstreamIds: ['3']
  }
];